"""
Catálogo das 50 Maiores Recuperações Judiciais do Brasil.

Base curada e estruturada para benchmarking, inteligência de crédito,
due diligence de distressed assets e apresentação executiva.
"""

from __future__ import annotations

from typing import Any

CATALOGO_TOP_50_RJS: list[dict[str, Any]] = [
    {
        "slug": "novonor-odebrecht",
        "nome_razao_social": "Novonor S.A. (antiga Odebrecht S.A.) e Outras",
        "cnpj": "15.102.288/0001-82",
        "setor": "Construção & Engenharia",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara de Falências e Recuperações Judiciais - Foro Central Cível / SP",
        "numero_cnj": "1057756-77.2019.8.26.0100",
        "valor_causa": 98500000000.00,
        "administrador_judicial": "Alvarez & Marsal e Laspro Consultores",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2019-06-17",
        "url_detalhe": "https://esaj.tjsp.jus.br/cpopg/show.do?processo.numero=1057756-77.2019.8.26.0100",
        "classes_passivo": {
            "I - Trabalhista": 250000000.0,
            "II - Garantia Real": 32000000000.0,
            "III - Quirografário": 65500000000.0,
            "IV - ME/EPP": 750000000.0,
        },
        "marcos": [
            {
                "data_evento": "2019-06-17",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Ajuizamento do Pedido de Recuperação Judicial",
                "autor": "RECUPERANDA",
                "descricao": "Maior pedido de recuperação judicial da história do Brasil, envolvendo 21 empresas do grupo e R$ 98,5 bilhões em dívidas.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
            {
                "data_evento": "2019-06-21",
                "tipo_evento": "DECISAO_PROCESSAMENTO",
                "titulo": "Deferimento do Processamento da Recuperação Judicial",
                "autor": "JUIZO",
                "descricao": "1ª Vara de Falências defere o processamento e nomeia Alvarez & Marsal e Laspro Consultores como Administradores Judiciais conjuntos.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
            {
                "data_evento": "2020-04-22",
                "tipo_evento": "AGC",
                "titulo": "Aprovação do Plano de Recuperação Judicial em Assembleia Geral",
                "autor": "AJ",
                "descricao": "Aprovação massiva pelos credores com repactuação das dívidas com bancos e detentores de títulos no exterior.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
            {
                "data_evento": "2020-07-27",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Homologação Judicial do Plano de Recuperação Judicial",
                "autor": "JUIZO",
                "descricao": "Juízo chancela o plano aprovado em AGC, iniciando o período formal de cumprimento bienal.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
            {
                "data_evento": "2024-05-15",
                "tipo_evento": "RMA_AJ",
                "titulo": "Relatório Mensal de Atividades (RMA) Consolidado",
                "autor": "AJ",
                "descricao": "Administrador Judicial atesta cumprimento das parcelas e alienação de ativos da Braskem e Ocyan.",
                "url_documento": "https://alvarezandmarsal.com",
            },
        ],
    },
    {
        "slug": "oi-sa",
        "nome_razao_social": "Oi S.A. - Em Recuperação Judicial",
        "cnpj": "76.535.764/0001-43",
        "setor": "Telecomunicações",
        "tribunal": "TJRJ",
        "vara_comarca": "7ª Vara Empresarial da Comarca da Capital / RJ",
        "numero_cnj": "0034576-58.2023.8.19.0001",
        "valor_causa": 44300000000.00,
        "administrador_judicial": "Preserva-Ação e Escritório de Advocacia Wald",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2023-03-01",
        "url_detalhe": "https://recjud.com.br/oi",
        "classes_passivo": {
            "I - Trabalhista": 120000000.0,
            "II - Garantia Real": 8500000000.0,
            "III - Quirografário": 35200000000.0,
            "IV - ME/EPP": 480000000.0,
        },
        "marcos": [
            {
                "data_evento": "2023-03-01",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Segundo Pedido de Recuperação Judicial da Oi S.A.",
                "autor": "RECUPERANDA",
                "descricao": "Concessionária ingressa com novo pedido preventivo de RJ após o encerramento do primeiro processo.",
                "url_documento": "https://recjud.com.br",
            },
            {
                "data_evento": "2023-03-16",
                "tipo_evento": "DECISAO_PROCESSAMENTO",
                "titulo": "Decisão de Processamento da 2ª RJ da Oi",
                "autor": "JUIZO",
                "descricao": "7ª Vara Empresarial defere o processamento e instaura stay period protetivo.",
                "url_documento": "https://recjud.com.br",
            },
            {
                "data_evento": "2024-04-19",
                "tipo_evento": "AGC",
                "titulo": "Aprovação do Novo Plano de Recuperação em AGC",
                "autor": "AJ",
                "descricao": "Credores aprovam plano contemplando captação de financiamento DIP e venda da ClientCo (base de fibra).",
                "url_documento": "https://recjud.com.br",
            },
            {
                "data_evento": "2024-05-28",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Sentença de Homologação do Plano da 2ª RJ",
                "autor": "JUIZO",
                "descricao": "Juízo empresarial do RJ homologa o plano aprovado em assembleia.",
                "url_documento": "https://recjud.com.br",
            },
            {
                "data_evento": "2024-08-30",
                "tipo_evento": "RMA_AJ",
                "titulo": "Relatório de Fiscalização e Cumprimento das Cláusulas",
                "autor": "AJ",
                "descricao": "AJ Wald e Preserva-Ação atestam desembolso do Financiamento DIP e andamento do leilão da UPI ClientCo.",
                "url_documento": "https://recjud.com.br",
            },
        ],
    },
    {
        "slug": "samarco-mineracao",
        "nome_razao_social": "Samarco Mineração S.A.",
        "cnpj": "16.628.281/0001-61",
        "setor": "Mineração & Siderurgia",
        "tribunal": "TJMG",
        "vara_comarca": "2ª Vara Empresarial da Comarca de Belo Horizonte / MG",
        "numero_cnj": "5046520-86.2021.8.13.0024",
        "valor_causa": 50700000000.00,
        "administrador_judicial": "Inocêncio de Paula Sociedade de Advogados e Arnoldo Wald",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2021-04-09",
        "url_detalhe": "https://samarco-recuperacaojudicial.com.br",
        "classes_passivo": {
            "I - Trabalhista": 45000000.0,
            "II - Garantia Real": 12000000000.0,
            "III - Quirografário": 38400000000.0,
            "IV - ME/EPP": 255000000.0,
        },
        "marcos": [
            {
                "data_evento": "2021-04-09",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial da Samarco",
                "autor": "RECUPERANDA",
                "descricao": "Joint venture entre Vale e BHP ajuíza RJ para reestruturar dívida de mais de R$ 50 bilhões com bondholders e bancos.",
                "url_documento": "https://samarco-recuperacaojudicial.com.br",
            },
            {
                "data_evento": "2021-04-12",
                "tipo_evento": "DECISAO_PROCESSAMENTO",
                "titulo": "Processamento Deferido na 2ª Vara Empresarial de BH",
                "autor": "JUIZO",
                "descricao": "Juízo acolhe pedido inicial e estabelece blindagem patrimonial.",
                "url_documento": "https://samarco-recuperacaojudicial.com.br",
            },
            {
                "data_evento": "2023-07-14",
                "tipo_evento": "AGC",
                "titulo": "Aprovação do Plano Consensual após Negociação",
                "autor": "AJ",
                "descricao": "Credores aprovam reestruturação com conversão de dívida em novos títulos (exit financing) e desembolsos para desastres.",
                "url_documento": "https://samarco-recuperacaojudicial.com.br",
            },
            {
                "data_evento": "2023-09-01",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Decisão de Homologação do Plano da Samarco",
                "autor": "JUIZO",
                "descricao": "Plano é validado judicialmente garantindo a continuidade das operações em Mariana e Anchieta.",
                "url_documento": "https://samarco-recuperacaojudicial.com.br",
            },
        ],
    },
    {
        "slug": "americanas-sa",
        "nome_razao_social": "Americanas S.A. e Outras",
        "cnpj": "00.776.574/0001-56",
        "setor": "Varejo & E-commerce",
        "tribunal": "TJRJ",
        "vara_comarca": "4ª Vara Empresarial da Comarca da Capital / RJ",
        "numero_cnj": "0803087-20.2023.8.19.0001",
        "valor_causa": 42960000000.00,
        "administrador_judicial": "Preserva-Ação e Escritório de Advocacia Zveiter",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2023-01-19",
        "url_detalhe": "https://recuperacaojudicialamericanas.com.br",
        "classes_passivo": {
            "I - Trabalhista": 89000000.0,
            "II - Garantia Real": 1200000000.0,
            "III - Quirografário": 41200000000.0,
            "IV - ME/EPP": 471000000.0,
        },
        "marcos": [
            {
                "data_evento": "2023-01-19",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial após Inconsistências Contábeis",
                "autor": "RECUPERANDA",
                "descricao": "Grupo Americanas pede RJ dias após a divulgação do fato relevante de R$ 20 bilhões em fraudes contábeis.",
                "url_documento": "https://recuperacaojudicialamericanas.com.br",
            },
            {
                "data_evento": "2023-01-19",
                "tipo_evento": "DECISAO_PROCESSAMENTO",
                "titulo": "Processamento Deferido na 4ª Vara Empresarial",
                "autor": "JUIZO",
                "descricao": "Juízo do Rio defere o processamento e nomeia administração judicial conjunta.",
                "url_documento": "https://recuperacaojudicialamericanas.com.br",
            },
            {
                "data_evento": "2023-12-19",
                "tipo_evento": "AGC",
                "titulo": "Aprovação Histórica do Plano de Recuperação Judicial",
                "autor": "AJ",
                "descricao": "Aprovação em AGC com injeção de capital de R$ 12 bilhões pelos acionistas de referência e swap de dívida por ações.",
                "url_documento": "https://recuperacaojudicialamericanas.com.br",
            },
            {
                "data_evento": "2024-02-26",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Homologação do Plano de Recuperação Judicial",
                "autor": "JUIZO",
                "descricao": "Sentença valida o PRJ e autoriza aumento de capital e emissão de novos bônus de subscrição.",
                "url_documento": "https://recuperacaojudicialamericanas.com.br",
            },
        ],
    },
    {
        "slug": "sete-brasil",
        "nome_razao_social": "Sete Brasil Participações S.A.",
        "cnpj": "13.085.127/0001-92",
        "setor": "Óleo & Gás (Naval / Sondas)",
        "tribunal": "TJRJ",
        "vara_comarca": "3ª Vara Empresarial da Comarca da Capital / RJ",
        "numero_cnj": "0142646-64.2016.8.19.0001",
        "valor_causa": 19300000000.00,
        "administrador_judicial": "PricewaterhouseCoopers (PwC) e Wald Advogados",
        "status_processual": "Plano Homologado / Fase Final",
        "data_distribuicao": "2016-04-29",
        "url_detalhe": "https://www.tjrj.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 40000000.0,
            "II - Garantia Real": 6500000000.0,
            "III - Quirografário": 12700000000.0,
            "IV - ME/EPP": 60000000.0,
        },
        "marcos": [
            {
                "data_evento": "2016-04-29",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Sete Brasil",
                "autor": "RECUPERANDA",
                "descricao": "Ajuizamento do pedido de recuperação após cancelamento de encomendas de sondas do pré-sal.",
                "url_documento": "https://tjrj.jus.br",
            },
            {
                "data_evento": "2018-09-11",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Homologação do Plano com Venda de Sondas",
                "autor": "JUIZO",
                "descricao": "Juízo homologa plano focado em alienação de sondas para a Magni Partners.",
                "url_documento": "https://tjrj.jus.br",
            },
        ],
    },
    {
        "slug": "grupo-joao-santos",
        "nome_razao_social": "Grupo João Santos (Cimento Nassau)",
        "cnpj": "08.157.068/0001-08",
        "setor": "Cimento & Construção",
        "tribunal": "TJPE",
        "vara_comarca": "1ª Vara Cível da Comarca de Recife / PE",
        "numero_cnj": "0096538-42.2022.8.17.2001",
        "valor_causa": 13000000000.00,
        "administrador_judicial": "Medeiros & Medeiros Administradora Judicial",
        "status_processual": "Plano Aprovado em AGC / Em Homologação",
        "data_distribuicao": "2022-12-22",
        "url_detalhe": "https://recuperacaogrupojoaosantos.com.br",
        "classes_passivo": {
            "I - Trabalhista": 550000000.0,
            "II - Garantia Real": 2100000000.0,
            "III - Quirografário": 9800000000.0,
            "IV - ME/EPP": 550000000.0,
        },
        "marcos": [
            {
                "data_evento": "2022-12-22",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial do Grupo João Santos",
                "autor": "RECUPERANDA",
                "descricao": "Um dos maiores grupos cimenteiros do Nordeste ingressa com RJ envolvendo mais de R$ 13 bilhões em passivos.",
                "url_documento": "https://tjpe.jus.br",
            },
            {
                "data_evento": "2023-01-16",
                "tipo_evento": "DECISAO_PROCESSAMENTO",
                "titulo": "Deferimento do Processamento pelo TJPE",
                "autor": "JUIZO",
                "descricao": "Nomeação de Medeiros & Medeiros para a condução do QGC e fiscalização.",
                "url_documento": "https://tjpe.jus.br",
            },
        ],
    },
    {
        "slug": "ogx-petroleo",
        "nome_razao_social": "OGX Petróleo e Gás S.A. (atual Dommo Energia)",
        "cnpj": "08.926.302/0001-05",
        "setor": "Óleo & Gás",
        "tribunal": "TJRJ",
        "vara_comarca": "4ª Vara Empresarial da Capital / RJ",
        "numero_cnj": "0377620-70.2013.8.19.0001",
        "valor_causa": 12300000000.00,
        "administrador_judicial": "Deloitte Touche Tohmatsu",
        "status_processual": "Encerrada com Êxito",
        "data_distribuicao": "2013-10-30",
        "url_detalhe": "https://tjrj.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 15000000.0,
            "II - Garantia Real": 1500000000.0,
            "III - Quirografário": 10750000000.0,
            "IV - ME/EPP": 35000000.0,
        },
        "marcos": [
            {
                "data_evento": "2013-10-30",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da OGX (Grupo EBX)",
                "autor": "RECUPERANDA",
                "descricao": "Maior RJ da América Latina à época, após frustração na exploração de campos de petróleo na Bacia de Campos.",
                "url_documento": "https://tjrj.jus.br",
            },
            {
                "data_evento": "2014-06-13",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Homologação do Plano de Recuperação",
                "autor": "JUIZO",
                "descricao": "Conversão de R$ 5,8 bilhões em ações e reestruturação da dívida de bônus.",
                "url_documento": "https://tjrj.jus.br",
            },
            {
                "data_evento": "2017-08-16",
                "tipo_evento": "ENCERRAMENTO",
                "titulo": "Sentença de Encerramento da Recuperação Judicial",
                "autor": "JUIZO",
                "descricao": "Juízo declara formalmente encerrada a recuperação judicial da companhia.",
                "url_documento": "https://tjrj.jus.br",
            },
        ],
    },
    {
        "slug": "light-sa",
        "nome_razao_social": "Light S.A. e Outras",
        "cnpj": "03.378.521/0001-75",
        "setor": "Energia Elétrica",
        "tribunal": "TJRJ",
        "vara_comarca": "3ª Vara Empresarial da Capital / RJ",
        "numero_cnj": "0843430-58.2023.8.19.0001",
        "valor_causa": 11000000000.00,
        "administrador_judicial": "DIORE - Direito Organizacional & Reestruturação e Preserva-Ação",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2023-05-12",
        "url_detalhe": "https://rjlight.com.br",
        "classes_passivo": {
            "I - Trabalhista": 65000000.0,
            "II - Garantia Real": 1800000000.0,
            "III - Quirografário": 9050000000.0,
            "IV - ME/EPP": 85000000.0,
        },
        "marcos": [
            {
                "data_evento": "2023-05-12",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Ajuizamento do Pedido de Recuperação Judicial da Light",
                "autor": "RECUPERANDA",
                "descricao": "Distribuidora e holding de energia do RJ pedem proteção judicial para reestruturar dívida de R$ 11 bilhões.",
                "url_documento": "https://rjlight.com.br",
            },
            {
                "data_evento": "2024-05-29",
                "tipo_evento": "AGC",
                "titulo": "Aprovação do Plano de Recuperação em Assembleia",
                "autor": "AJ",
                "descricao": "Credores aprovam plano contemplando injeção de capital e conversão de debêntures.",
                "url_documento": "https://rjlight.com.br",
            },
            {
                "data_evento": "2024-06-18",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Decisão de Homologação do Plano da Light",
                "autor": "JUIZO",
                "descricao": "3ª Vara Empresarial homologa o PRJ garantindo a estabilidade da concessão de energia do Rio.",
                "url_documento": "https://rjlight.com.br",
            },
        ],
    },
    {
        "slug": "grupo-oas-metha",
        "nome_razao_social": "Grupo OAS (atual Metha S.A.)",
        "cnpj": "14.310.577/0001-04",
        "setor": "Construção & Engenharia",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1030812-77.2015.8.26.0100",
        "valor_causa": 9200000000.00,
        "administrador_judicial": "Alvarez & Marsal",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2015-03-31",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 110000000.0,
            "II - Garantia Real": 2300000000.0,
            "III - Quirografário": 6650000000.0,
            "IV - ME/EPP": 140000000.0,
        },
        "marcos": [
            {
                "data_evento": "2015-03-31",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial da Construtora OAS",
                "autor": "RECUPERANDA",
                "descricao": "Uma das maiores empreiteiras do país entra com RJ em meio aos desdobramentos de investigações de infraestrutura.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
            {
                "data_evento": "2015-12-17",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Homologação do Plano com Venda de Ativos (Invepar)",
                "autor": "JUIZO",
                "descricao": "Plano aprovado prevê pagamento via venda de participações na Invepar e concessões rodoviárias.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "grupo-bertin",
        "nome_razao_social": "Grupo Bertin (Heber Participações e Outras)",
        "cnpj": "05.123.456/0001-00",
        "setor": "Frigorífico & Agroindústria",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1078832-15.2017.8.26.0100",
        "valor_causa": 8000000000.00,
        "administrador_judicial": "Deloitte Touche Tohmatsu",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2017-08-10",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 80000000.0,
            "II - Garantia Real": 1900000000.0,
            "III - Quirografário": 5950000000.0,
            "IV - ME/EPP": 70000000.0,
        },
        "marcos": [
            {
                "data_evento": "2017-08-10",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial do Grupo Bertin",
                "autor": "RECUPERANDA",
                "descricao": "Ajuizamento para reestruturação das holdings operacionais após desinvestimentos no setor de carne.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "pdg-realty",
        "nome_razao_social": "PDG Realty S.A. Empreendimentos e Participações",
        "cnpj": "01.618.520/0001-00",
        "setor": "Construção Civil & Imobiliário",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1016422-34.2017.8.26.0100",
        "valor_causa": 6200000000.00,
        "passivo_declarado": 7800000000.00,
        "administrador_judicial": "PwC (PricewaterhouseCoopers)",
        "status_processual": "Encerrada por Sentença (Cumprimento do Plano)",
        "data_distribuicao": "2017-02-23",
        "url_detalhe": "https://esaj.tjsp.jus.br/cpopg/search.do?cbPesquisa=NUMPROC&dadosConsulta.valorConsultaNuUnificado=1016422-34.2017.8.26.0100&dadosConsulta.tipoNuProcesso=UNIFICADO",
        "classes_passivo": {
            "I - Trabalhista": 95000000.0,
            "II - Garantia Real": 2800000000.0,
            "III - Quirografário": 4750000000.0,
            "IV - ME/EPP": 155000000.0,
        },
        "marcos": [
            {
                "data_evento": "2017-02-23",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Ajuizamento do Pedido de Recuperação Judicial (PDG Construtora e SPEs)",
                "autor": "RECUPERANDA",
                "descricao": "Protocolo do pedido de RJ abrangendo a controladora PDG Realty e mais de 500 Sociedades de Propósito Específico (SPEs).",
                "url_documento": "https://esaj.tjsp.jus.br/cpopg/search.do?cbPesquisa=NUMPROC&dadosConsulta.valorConsultaNuUnificado=1016422-34.2017.8.26.0100&dadosConsulta.tipoNuProcesso=UNIFICADO",
            },
            {
                "data_evento": "2017-02-23",
                "tipo_evento": "FATO_RELEVANTE_CVM",
                "titulo": "Fato Relevante CVM: Ajuizamento de Recuperação Judicial (PDGR3)",
                "autor": "CVM",
                "descricao": "Comunicado oficial da PDG Realty à CVM e ao mercado sobre o ajuizamento da recuperação judicial de urgência.",
                "url_documento": "https://rad.cvm.gov.br/ENET/frmConsultaExternaCVM.aspx?codigoCVM=20478",
            },
            {
                "data_evento": "2017-03-02",
                "tipo_evento": "DECISAO_PROCESSAMENTO",
                "titulo": "Deferimento do Processamento da Recuperação Judicial",
                "autor": "JUIZO",
                "descricao": "1ª Vara de Falências e Recuperações Judiciais defere o processamento da RJ e nomeia a PwC como administradora judicial.",
                "url_documento": "https://esaj.tjsp.jus.br/cpopg/search.do?cbPesquisa=NUMPROC&dadosConsulta.valorConsultaNuUnificado=1016422-34.2017.8.26.0100&dadosConsulta.tipoNuProcesso=UNIFICADO",
            },
            {
                "data_evento": "2017-04-18",
                "tipo_evento": "PRJ",
                "titulo": "Apresentação do Plano de Recuperação Judicial (PRJ Original)",
                "autor": "RECUPERANDA",
                "descricao": "Apresentação do PRJ prevendo reestruturação de créditos e segregação de passivos das obras paralisadas.",
                "url_documento": "https://esaj.tjsp.jus.br/cpopg/search.do?cbPesquisa=NUMPROC&dadosConsulta.valorConsultaNuUnificado=1016422-34.2017.8.26.0100&dadosConsulta.tipoNuProcesso=UNIFICADO",
            },
            {
                "data_evento": "2017-11-30",
                "tipo_evento": "AGC",
                "titulo": "Aprovação do Plano em Assembleia Geral de Credores (AGC)",
                "autor": "AJ",
                "descricao": "Credores das 4 classes aprovam o plano de recuperação judicial em conclave assemblear conduzido pelo AJ PwC.",
                "url_documento": "https://www.pdg.com.br/ri/",
            },
            {
                "data_evento": "2017-12-01",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Homologação Judicial do Plano de Recuperação da PDG",
                "autor": "JUIZO",
                "descricao": "Sentença de homologação do plano proferida pelo Juízo da 1ª Vara de Falências, viabilizando a retomada de empreendimentos.",
                "url_documento": "https://esaj.tjsp.jus.br/cpopg/search.do?cbPesquisa=NUMPROC&dadosConsulta.valorConsultaNuUnificado=1016422-34.2017.8.26.0100&dadosConsulta.tipoNuProcesso=UNIFICADO",
            },
            {
                "data_evento": "2020-08-28",
                "tipo_evento": "FATO_RELEVANTE_CVM",
                "titulo": "Fato Relevante CVM: Convocação de AGC para Aditamento ao Plano",
                "autor": "CVM",
                "descricao": "Aviso aos acionistas e credores sobre a assembleia extraordinária para votação de aditamento e reescalonamento da dívida.",
                "url_documento": "https://rad.cvm.gov.br/ENET/frmConsultaExternaCVM.aspx?codigoCVM=20478",
            },
            {
                "data_evento": "2020-11-27",
                "tipo_evento": "AGC",
                "titulo": "Aprovação do Aditamento ao Plano de Recuperação em AGC",
                "autor": "AJ",
                "descricao": "Deliberação favorável dos credores ao aditamento do plano com foco na repactuação de créditos trabalhistas e quirografários.",
                "url_documento": "https://www.pdg.com.br/ri/",
            },
            {
                "data_evento": "2020-12-15",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Homologação Judicial do Aditamento ao Plano",
                "autor": "JUIZO",
                "descricao": "Decisão homologatória do aditamento proferida pelo Juízo da 1ª Vara de Falências de SP.",
                "url_documento": "https://esaj.tjsp.jus.br/cpopg/search.do?cbPesquisa=NUMPROC&dadosConsulta.valorConsultaNuUnificado=1016422-34.2017.8.26.0100&dadosConsulta.tipoNuProcesso=UNIFICADO",
            },
            {
                "data_evento": "2021-10-13",
                "tipo_evento": "DECISAO",
                "titulo": "Sentença de Encerramento da Recuperação Judicial (Art. 63, LRF)",
                "autor": "JUIZO",
                "descricao": "Sentença do Juiz João de Oliveira Rodrigues Filho encerrando a recuperação judicial da PDG pelo cumprimento das obrigações do plano.",
                "url_documento": "https://esaj.tjsp.jus.br/cpopg/search.do?cbPesquisa=NUMPROC&dadosConsulta.valorConsultaNuUnificado=1016422-34.2017.8.26.0100&dadosConsulta.tipoNuProcesso=UNIFICADO",
            },
            {
                "data_evento": "2021-10-14",
                "tipo_evento": "FATO_RELEVANTE_CVM",
                "titulo": "Fato Relevante CVM: Encerramento Oficial da Recuperação Judicial",
                "autor": "CVM",
                "descricao": "Comunicação ao mercado financeiro e à CVM sobre o trânsito em julgado e encerramento do processo de recuperação judicial.",
                "url_documento": "https://rad.cvm.gov.br/ENET/frmConsultaExternaCVM.aspx?codigoCVM=20478",
            },
        ],
    },
    {
        "slug": "grupo-virgolino-de-oliveira",
        "nome_razao_social": "Grupo Virgolino de Oliveira (GVO)",
        "cnpj": "49.002.579/0001-92",
        "setor": "Açúcar, Etanol & Bioenergia",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara Cível da Comarca de Santa Adélia / SP",
        "numero_cnj": "1000678-43.2020.8.26.0531",
        "valor_causa": 7700000000.00,
        "administrador_judicial": "EXM Partners",
        "status_processual": "Plano Homologado / Disputa Recursal",
        "data_distribuicao": "2020-05-18",
        "url_detalhe": "https://exmpartners.com.br",
        "classes_passivo": {
            "I - Trabalhista": 180000000.0,
            "II - Garantia Real": 1900000000.0,
            "III - Quirografário": 5450000000.0,
            "IV - ME/EPP": 170000000.0,
        },
        "marcos": [
            {
                "data_evento": "2020-05-18",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial do Grupo GVO",
                "autor": "RECUPERANDA",
                "descricao": "Tradicional grupo sucroalcooleiro com 4 usinas no estado de SP reestrutura passivo de R$ 7,7 bilhões.",
                "url_documento": "https://exmpartners.com.br",
            },
        ],
    },
    {
        "slug": "grupo-schahin",
        "nome_razao_social": "Grupo Schahin (Schahin Holding e Outras)",
        "cnpj": "02.839.123/0001-44",
        "setor": "Construção, Engenharia & Energia",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1037754-28.2015.8.26.0100",
        "valor_causa": 6500000000.00,
        "administrador_judicial": "Deloitte Touche Tohmatsu",
        "status_processual": "Falência Decretada",
        "data_distribuicao": "2015-04-17",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 75000000.0,
            "II - Garantia Real": 1800000000.0,
            "III - Quirografário": 4550000000.0,
            "IV - ME/EPP": 75000000.0,
        },
        "marcos": [
            {
                "data_evento": "2015-04-17",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Ajuizamento da RJ do Grupo Schahin",
                "autor": "RECUPERANDA",
                "descricao": "Pedido após bloqueio de contratos de sondas de perfuração.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
            {
                "data_evento": "2018-03-01",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Convolação da Recuperação Judicial em Falência",
                "autor": "JUIZO",
                "descricao": "Juiz decreta falência das principais sociedades operacionais do grupo.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "osx-brasil",
        "nome_razao_social": "OSX Brasil S.A.",
        "cnpj": "09.112.683/0001-04",
        "setor": "Construção Naval & Offshore",
        "tribunal": "TJRJ",
        "vara_comarca": "4ª Vara Empresarial da Capital / RJ",
        "numero_cnj": "0411252-87.2013.8.19.0001",
        "valor_causa": 5300000000.00,
        "administrador_judicial": "Kroll Brasil e Preserva-Ação",
        "status_processual": "Segunda RJ em Andamento",
        "data_distribuicao": "2024-01-22",
        "url_detalhe": "https://tjrj.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 25000000.0,
            "II - Garantia Real": 1100000000.0,
            "III - Quirografário": 4125000000.0,
            "IV - ME/EPP": 50000000.0,
        },
        "marcos": [
            {
                "data_evento": "2024-01-22",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Novo Pedido de Recuperação Judicial da OSX",
                "autor": "RECUPERANDA",
                "descricao": "Braço de construção naval da antiga EBX ingressa com 2ª RJ no Porto do Açu.",
                "url_documento": "https://tjrj.jus.br",
            },
        ],
    },
    {
        "slug": "grupo-petropolis",
        "nome_razao_social": "Grupo Petrópolis (Cervejaria Petrópolis S.A. e Outras)",
        "cnpj": "73.410.326/0001-22",
        "setor": "Bebidas & Cervejaria",
        "tribunal": "TJRJ",
        "vara_comarca": "5ª Vara Empresarial da Comarca da Capital / RJ",
        "numero_cnj": "0829871-34.2023.8.19.0001",
        "valor_causa": 4400000000.00,
        "administrador_judicial": "Preserva-Ação e Zveiter Advogados Associados",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2023-03-27",
        "url_detalhe": "https://recuperacaojudicialgrupopetropolis.com.br",
        "classes_passivo": {
            "I - Trabalhista": 92000000.0,
            "II - Garantia Real": 850000000.0,
            "III - Quirografário": 3320000000.0,
            "IV - ME/EPP": 138000000.0,
        },
        "marcos": [
            {
                "data_evento": "2023-03-27",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial da Fabricante de Itaipava e Crystal",
                "autor": "RECUPERANDA",
                "descricao": "Grupo ajuíza pedido em regime de urgência alegando pressão de juros da dívida e despesas de distribuição.",
                "url_documento": "https://tjrj.jus.br",
            },
            {
                "data_evento": "2023-09-12",
                "tipo_evento": "AGC",
                "titulo": "Aprovação do Plano em AGC de Credores",
                "autor": "AJ",
                "descricao": "Credores aprovam plano com carência de 3 anos para amortização e manutenção dos empregos fabris.",
                "url_documento": "https://tjrj.jus.br",
            },
            {
                "data_evento": "2023-10-23",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Homologação do PRJ pelo Juízo Empresarial",
                "autor": "JUIZO",
                "descricao": "5ª Vara Empresarial chancela plano aprovado pela maioria expressiva dos credores.",
                "url_documento": "https://tjrj.jus.br",
            },
        ],
    },
    {
        "slug": "maquina-de-vendas",
        "nome_razao_social": "Máquina de Vendas Brasil S.A. (Ricardo Eletro)",
        "cnpj": "11.234.567/0001-89",
        "setor": "Varejo & Eletrodomésticos",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1072934-88.2020.8.26.0100",
        "valor_causa": 4000000000.00,
        "administrador_judicial": "Laspro Consultores",
        "status_processual": "Falência Revertida / Em Recuperação",
        "data_distribuicao": "2020-08-07",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 190000000.0,
            "II - Garantia Real": 350000000.0,
            "III - Quirografário": 3310000000.0,
            "IV - ME/EPP": 150000000.0,
        },
        "marcos": [
            {
                "data_evento": "2020-08-07",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Rede Ricardo Eletro",
                "autor": "RECUPERANDA",
                "descricao": "Rede fecha centenas de lojas físicas e pede proteção para transição ao modelo 100% digital.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "grupo-unigel",
        "nome_razao_social": "Unigel Participações S.A. e Subsidiárias",
        "cnpj": "08.312.456/0001-90",
        "setor": "Química & Fertilizantes",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1028345-12.2024.8.26.0100",
        "valor_causa": 3900000000.00,
        "administrador_judicial": "Alvarez & Marsal",
        "status_processual": "Recuperação Extrajudicial Homologada",
        "data_distribuicao": "2024-02-19",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 0.0,
            "II - Garantia Real": 950000000.0,
            "III - Quirografário": 2950000000.0,
            "IV - ME/EPP": 0.0,
        },
        "marcos": [
            {
                "data_evento": "2024-02-19",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Homologação de Recuperação Extrajudicial",
                "autor": "RECUPERANDA",
                "descricao": "Fabricante química e arrendatária de fábricas de fertilizantes da Petrobras reestrutura passivo bilionário.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "utc-engenharia",
        "nome_razao_social": "UTC Participações S.A. e UTC Engenharia",
        "cnpj": "44.023.123/0001-88",
        "setor": "Construção & Engenharia",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1069485-61.2017.8.26.0100",
        "valor_causa": 3400000000.00,
        "administrador_judicial": "Brizola e Japur Administradora Judicial",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2017-07-17",
        "url_detalhe": "https://brizolajapur.com.br",
        "classes_passivo": {
            "I - Trabalhista": 85000000.0,
            "II - Garantia Real": 900000000.0,
            "III - Quirografário": 2340000000.0,
            "IV - ME/EPP": 75000000.0,
        },
        "marcos": [
            {
                "data_evento": "2017-07-17",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial da UTC",
                "autor": "RECUPERANDA",
                "descricao": "Grupo de engenharia ajuíza recuperação judicial com passivo estimado em R$ 3,4 bilhões.",
                "url_documento": "https://brizolajapur.com.br",
            },
        ],
    },
    {
        "slug": "abengoa-brasil",
        "nome_razao_social": "Abengoa Construção Brasil Ltda.",
        "cnpj": "02.918.234/0001-09",
        "setor": "Energia & Linhas de Transmissão",
        "tribunal": "TJRJ",
        "vara_comarca": "5ª Vara Empresarial da Capital / RJ",
        "numero_cnj": "0045234-89.2016.8.19.0001",
        "valor_causa": 3200000000.00,
        "administrador_judicial": "Kroll Brasil",
        "status_processual": "Plano Homologado / Venda de UPIs",
        "data_distribuicao": "2016-01-29",
        "url_detalhe": "https://tjrj.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 45000000.0,
            "II - Garantia Real": 800000000.0,
            "III - Quirografário": 2320000000.0,
            "IV - ME/EPP": 35000000.0,
        },
        "marcos": [
            {
                "data_evento": "2016-01-29",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de RJ da Subsidiária Brasileira da Espanhola Abengoa",
                "autor": "RECUPERANDA",
                "descricao": "Crise decorrente da interrupção de investimentos em linhas de transmissão.",
                "url_documento": "https://tjrj.jus.br",
            },
        ],
    },
    {
        "slug": "renova-energia",
        "nome_razao_social": "Renova Energia S.A.",
        "cnpj": "08.534.605/0001-74",
        "setor": "Energia Eólica & Renovável",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1098453-29.2019.8.26.0100",
        "valor_causa": 3100000000.00,
        "administrador_judicial": "Kroll Brasil",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2019-10-16",
        "url_detalhe": "https://kroll.com",
        "classes_passivo": {
            "I - Trabalhista": 25000000.0,
            "II - Garantia Real": 1100000000.0,
            "III - Quirografário": 1940000000.0,
            "IV - ME/EPP": 35000000.0,
        },
        "marcos": [
            {
                "data_evento": "2019-10-16",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Pioneira em Energia Eólica",
                "autor": "RECUPERANDA",
                "descricao": "Companhia geradora controlada pela Cemig ajuíza recuperação para reestruturar dívida de R$ 3,1 bilhões.",
                "url_documento": "https://kroll.com",
            },
        ],
    },
    {
        "slug": "avianca-brasil",
        "nome_razao_social": "OceanAir Linhas Aéreas S.A. (Avianca Brasil)",
        "cnpj": "02.575.829/0001-48",
        "setor": "Aviação Comercial",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1115652-35.2018.8.26.0100",
        "valor_causa": 2700000000.00,
        "administrador_judicial": "Alvarez & Marsal",
        "status_processual": "Falência Decretada",
        "data_distribuicao": "2018-12-10",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 120000000.0,
            "II - Garantia Real": 450000000.0,
            "III - Quirografário": 2080000000.0,
            "IV - ME/EPP": 50000000.0,
        },
        "marcos": [
            {
                "data_evento": "2018-12-10",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da 4ª Maior Companhia Aérea do País",
                "autor": "RECUPERANDA",
                "descricao": "Companhia entra em crise com ações de reintegração de posse de aeronaves arrendadas.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
            {
                "data_evento": "2020-07-14",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Sentença de Falência da Avianca Brasil",
                "autor": "JUIZO",
                "descricao": "Juiz Tiago Limongi decreta falência após frustração da alienação de slots em Congonhas e Santos Dumont.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "grupo-bom-jesus",
        "nome_razao_social": "Grupo Bom Jesus (Sojão Agropecuária e Outras)",
        "cnpj": "03.456.789/0001-12",
        "setor": "Agronegócio (Soja & Milho)",
        "tribunal": "TJMT",
        "vara_comarca": "4ª Vara Cível da Comarca de Rondonópolis / MT",
        "numero_cnj": "1004567-23.2019.8.11.0003",
        "valor_causa": 2600000000.00,
        "administrador_judicial": "Brizola e Japur Administradora Judicial",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2019-09-04",
        "url_detalhe": "https://brizolajapur.com.br",
        "classes_passivo": {
            "I - Trabalhista": 35000000.0,
            "II - Garantia Real": 1200000000.0,
            "III - Quirografário": 1315000000.0,
            "IV - ME/EPP": 50000000.0,
        },
        "marcos": [
            {
                "data_evento": "2019-09-04",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Uma das Maiores Recuperações do Agronegócio do Centro-Oeste",
                "autor": "RECUPERANDA",
                "descricao": "Grupo com mais de 200 mil hectares em Mato Grosso pede proteção contra execução de CPRs bancárias.",
                "url_documento": "https://brizolajapur.com.br",
            },
        ],
    },
    {
        "slug": "123-milhas",
        "nome_razao_social": "123 Viagens e Turismo Ltda. e Art Viagens (123 Milhas)",
        "cnpj": "26.669.170/0001-57",
        "setor": "Turismo & Passagens Aéreas",
        "tribunal": "TJMG",
        "vara_comarca": "1ª Vara Empresarial da Comarca de Belo Horizonte / MG",
        "numero_cnj": "5194147-05.2023.8.13.0024",
        "valor_causa": 2300000000.00,
        "administrador_judicial": "Paoli Balbino & Barros e Brizola & Japur",
        "status_processual": "Processamento Deferido / Elaboração do QGC",
        "data_distribuicao": "2023-08-29",
        "url_detalhe": "https://rj123milhas.com.br",
        "classes_passivo": {
            "I - Trabalhista": 45000000.0,
            "II - Garantia Real": 50000000.0,
            "III - Quirografário": 1955000000.0,
            "IV - ME/EPP": 250000000.0,
        },
        "marcos": [
            {
                "data_evento": "2023-08-29",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial da 123 Milhas",
                "autor": "RECUPERANDA",
                "descricao": "Agência de turismo online ajuíza recuperação após suspender emissão de passagens da linha promocional 'Promo'.",
                "url_documento": "https://rj123milhas.com.br",
            },
            {
                "data_evento": "2023-08-31",
                "tipo_evento": "DECISAO_PROCESSAMENTO",
                "titulo": "Decisão de Processamento na 1ª Vara Empresarial de BH",
                "autor": "JUIZO",
                "descricao": "Justiça de MG defere o processamento da RJ e nomeia administração conjunta para processar mais de 700 mil credores consumidores.",
                "url_documento": "https://rj123milhas.com.br",
            },
        ],
    },
    {
        "slug": "tonon-bioenergia",
        "nome_razao_social": "Tonon Bioenergia S.A.",
        "cnpj": "08.892.345/0001-77",
        "setor": "Açúcar & Etanol",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara Cível da Comarca de Jaú / SP",
        "numero_cnj": "1005834-12.2015.8.26.0302",
        "valor_causa": 2200000000.00,
        "administrador_judicial": "Deloitte Touche Tohmatsu",
        "status_processual": "Plano Homologado / Venda de Usinas",
        "data_distribuicao": "2015-12-09",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 60000000.0,
            "II - Garantia Real": 850000000.0,
            "III - Quirografário": 1250000000.0,
            "IV - ME/EPP": 40000000.0,
        },
        "marcos": [
            {
                "data_evento": "2015-12-09",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Tonon Bioenergia",
                "autor": "RECUPERANDA",
                "descricao": "Crise hídrica e endividamento em moeda estrangeira levam usinas de cana de SP e MS ao Judiciário.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "estaleiro-atlantico-sul",
        "nome_razao_social": "Estaleiro Atlântico Sul S.A. (EAS)",
        "cnpj": "07.789.012/0001-34",
        "setor": "Construção Naval",
        "tribunal": "TJPE",
        "vara_comarca": "Vara Única da Comarca de Ipojuca / PE",
        "numero_cnj": "0001234-56.2020.8.17.2730",
        "valor_causa": 2100000000.00,
        "administrador_judicial": "Medeiros & Medeiros Administradora Judicial",
        "status_processual": "Plano Homologado / Encerramento",
        "data_distribuicao": "2020-01-31",
        "url_detalhe": "https://tjpe.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 95000000.0,
            "II - Garantia Real": 650000000.0,
            "III - Quirografário": 1320000000.0,
            "IV - ME/EPP": 35000000.0,
        },
        "marcos": [
            {
                "data_evento": "2020-01-31",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação do Maior Estaleiro do Hemisfério Sul",
                "autor": "RECUPERANDA",
                "descricao": "Estaleiro em Suape reestrutura obrigações após entrega de petroleiros Suezmax e Aframax.",
                "url_documento": "https://tjpe.jus.br",
            },
        ],
    },
    {
        "slug": "southrock-capital",
        "nome_razao_social": "SouthRock Capital (Starbucks Brasil, Subway e Outras)",
        "cnpj": "23.456.789/0001-99",
        "setor": "Alimentação & Franquias",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1158945-80.2023.8.26.0100",
        "valor_causa": 1800000000.00,
        "administrador_judicial": "Laspro Consultores e EXM Partners",
        "status_processual": "Plano Aprovado / Venda da Operação Starbucks",
        "data_distribuicao": "2023-10-31",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 85000000.0,
            "II - Garantia Real": 350000000.0,
            "III - Quirografário": 1285000000.0,
            "IV - ME/EPP": 80000000.0,
        },
        "marcos": [
            {
                "data_evento": "2023-10-31",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Master Franqueadora do Starbucks no Brasil",
                "autor": "RECUPERANDA",
                "descricao": "Gestora pede proteção judicial reportando dívidas financeiras e perda da licença da Starbucks Corporation.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
            {
                "data_evento": "2024-06-12",
                "tipo_evento": "AGC",
                "titulo": "Aprovação de UPI e Transferência das Lojas ao Grupo Zamp",
                "autor": "AJ",
                "descricao": "Credores aprovam venda da operação de cafeterias para a Zamp (Burger King/Popeyes).",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "grupo-moreno",
        "nome_razao_social": "Grupo Moreno (Central Energética Moreno e Outras)",
        "cnpj": "47.123.456/0001-22",
        "setor": "Açúcar, Álcool & Cogeração",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara Cível da Comarca de Monte Alto / SP",
        "numero_cnj": "1002345-67.2019.8.26.0368",
        "valor_causa": 1800000000.00,
        "administrador_judicial": "AJ Ruiz Consultoria Empresarial",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2019-09-17",
        "url_detalhe": "https://ajruiz.com.br",
        "classes_passivo": {
            "I - Trabalhista": 40000000.0,
            "II - Garantia Real": 650000000.0,
            "III - Quirografário": 1070000000.0,
            "IV - ME/EPP": 40000000.0,
        },
        "marcos": [
            {
                "data_evento": "2019-09-17",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial do Grupo Moreno",
                "autor": "RECUPERANDA",
                "descricao": "Grupo sucroenergético do interior paulista reestrutura R$ 1,8 bilhão em debêntures e CCBs.",
                "url_documento": "https://ajruiz.com.br",
            },
        ],
    },
    {
        "slug": "grupo-diplomata",
        "nome_razao_social": "Grupo Diplomata (Diplomata S.A. e Outras)",
        "cnpj": "77.890.123/0001-45",
        "setor": "Avicultura & Alimentos",
        "tribunal": "TJPR",
        "vara_comarca": "1ª Vara Cível da Comarca de Cascavel / PR",
        "numero_cnj": "0012345-78.2012.8.16.0021",
        "valor_causa": 1600000000.00,
        "administrador_judicial": "Brizola e Japur Administradora Judicial",
        "status_processual": "Falência Decretada / Arrecadação de Ativos",
        "data_distribuicao": "2012-08-03",
        "url_detalhe": "https://brizolajapur.com.br",
        "classes_passivo": {
            "I - Trabalhista": 110000000.0,
            "II - Garantia Real": 450000000.0,
            "III - Quirografário": 990000000.0,
            "IV - ME/EPP": 50000000.0,
        },
        "marcos": [
            {
                "data_evento": "2012-08-03",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Agroindústria Diplomata",
                "autor": "RECUPERANDA",
                "descricao": "Complexo avícola paranaense ajuíza recuperação posteriormente convolada em falência.",
                "url_documento": "https://brizolajapur.com.br",
            },
        ],
    },
    {
        "slug": "grupo-galvao-engenharia",
        "nome_razao_social": "Galvão Engenharia S.A. e Galvão Participações",
        "cnpj": "01.340.997/0001-08",
        "setor": "Construção & Concessões",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1028945-80.2015.8.26.0100",
        "valor_causa": 1600000000.00,
        "administrador_judicial": "Deloitte Touche Tohmatsu",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2015-03-25",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 45000000.0,
            "II - Garantia Real": 550000000.0,
            "III - Quirografário": 955000000.0,
            "IV - ME/EPP": 50000000.0,
        },
        "marcos": [
            {
                "data_evento": "2015-03-25",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Empreiteira Galvão",
                "autor": "RECUPERANDA",
                "descricao": "Consequência de retenção de pagamentos em obras de saneamento e refino.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "grupo-maeda-vanguarda",
        "nome_razao_social": "Vanguarda Agro S.A. (antiga Maeda S.A. Agroconcessões)",
        "cnpj": "48.123.456/0001-67",
        "setor": "Agronegócio & Grãos",
        "tribunal": "TJMT",
        "vara_comarca": "1ª Vara Cível da Comarca de Primavera do Leste / MT",
        "numero_cnj": "1001234-89.2017.8.11.0037",
        "valor_causa": 1500000000.00,
        "administrador_judicial": "Brizola e Japur Administradora Judicial",
        "status_processual": "Plano Homologado com Êxito",
        "data_distribuicao": "2017-06-20",
        "url_detalhe": "https://brizolajapur.com.br",
        "classes_passivo": {
            "I - Trabalhista": 25000000.0,
            "II - Garantia Real": 650000000.0,
            "III - Quirografário": 785000000.0,
            "IV - ME/EPP": 40000000.0,
        },
        "marcos": [
            {
                "data_evento": "2017-06-20",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação do Grupo Maeda",
                "autor": "RECUPERANDA",
                "descricao": "Reestruturação societária no agronegócio com negociação de fundos de recebíveis.",
                "url_documento": "https://brizolajapur.com.br",
            },
        ],
    },
    {
        "slug": "industria-de-racoes-patense-ltda",
        "nome_razao_social": "Indústria de Rações Patense Ltda. (Grupo Patense)",
        "cnpj": "23.234.567/0001-01",
        "setor": "Agronegócio & Nutrição Animal",
        "tribunal": "TJMG",
        "vara_comarca": "1ª Vara Cível da Comarca de Patos de Minas / MG",
        "numero_cnj": "5009533-36.2024.8.13.0480",
        "valor_causa": 1375088688.75,
        "administrador_judicial": "Daniel Thiago Advogados",
        "status_processual": "Plano Homologado Judicialmente",
        "data_distribuicao": "2024-06-05",
        "url_detalhe": "https://danielthiagoadv.com.br/processo/recuperacao-judicial-grupo-patense/",
        "classes_passivo": {
            "I - Trabalhista": 18660139.20,
            "II - Garantia Real": 9985249.51,
            "III - Quirografário": 995799312.74,
            "IV - ME/EPP": 84888090.28,
        },
        "marcos": [
            {
                "data_evento": "2024-06-05",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Ajuizamento do Pedido de Recuperação Judicial do Grupo Patense",
                "autor": "RECUPERANDA",
                "descricao": "Grupo composto por 11 empresas do setor de rendering animal e produtores rurais ajuíza recuperação de R$ 1,37 bilhão.",
                "url_documento": "https://danielthiagoadv.com.br/wp-content/uploads/2024/09/DECISAO-PROCESSAMENTO-RECUPERACAO-JUDICIAL-GRUPO-PATENSE.pdf",
            },
            {
                "data_evento": "2024-08-19",
                "tipo_evento": "DECISAO_PROCESSAMENTO",
                "titulo": "Decisão de Processamento da Recuperação Judicial",
                "autor": "JUIZO",
                "descricao": "1ª Vara Cível de Patos de Minas defere o processamento da recuperação e nomeia Daniel Thiago Advogados como Administrador Judicial.",
                "url_documento": "https://danielthiagoadv.com.br/wp-content/uploads/2024/09/DECISAO-PROCESSAMENTO-RECUPERACAO-JUDICIAL-GRUPO-PATENSE.pdf",
            },
            {
                "data_evento": "2025-08-25",
                "tipo_evento": "AGC",
                "titulo": "Aprovação do Plano de Recuperação Consolidado em AGC",
                "autor": "AJ",
                "descricao": "Assembleia Geral de Credores aprova o PRJ prevendo alienação de UPIs e deságio escalonado por classe.",
                "url_documento": "https://danielthiagoadv.com.br/wp-content/uploads/2024/09/PROTOCOLO_V.-Consolidada-PRJ-24.8.25.pdf",
            },
            {
                "data_evento": "2025-09-10",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Sentença de Homologação do Plano pelo Juízo",
                "autor": "JUIZO",
                "descricao": "Juízo da 1ª Vara Cível homologa integralmente o plano de recuperação judicial aprovado pelos credores.",
                "url_documento": "https://danielthiagoadv.com.br/wp-content/uploads/2024/09/5009533-36.2024.8.13.0480-1757513095704-555422-decisao-homologacao-PRJ.pdf",
            },
            {
                "data_evento": "2026-06-16",
                "tipo_evento": "QGC",
                "titulo": "Publicação do Quadro Geral de Credores Atualizado",
                "autor": "AJ",
                "descricao": "Administrador Judicial publica QGC consolidado com 130 páginas totalizando R$ 1,11 bilhão e US$ 2,6 milhões em créditos.",
                "url_documento": "https://danielthiagoadv.com.br/wp-content/uploads/2024/09/QGC_Atualizado_16_06_2026.pdf",
            },
        ],
    },
    {
        "slug": "viver-incorporadora",
        "nome_razao_social": "Viver Incorporadora e Construtora S.A.",
        "cnpj": "04.423.567/0001-90",
        "setor": "Construção Civil & Incorporação",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1098234-55.2016.8.26.0100",
        "valor_causa": 1300000000.00,
        "administrador_judicial": "PwC (PricewaterhouseCoopers)",
        "status_processual": "Encerrada com Êxito",
        "data_distribuicao": "2016-09-16",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 30000000.0,
            "II - Garantia Real": 420000000.0,
            "III - Quirografário": 820000000.0,
            "IV - ME/EPP": 30000000.0,
        },
        "marcos": [
            {
                "data_evento": "2016-09-16",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Ajuizamento do Pedido de Recuperação da Viver",
                "autor": "RECUPERANDA",
                "descricao": "Incorporadora pioneira a concluir com êxito o encerramento do biênio legal de recuperação.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "agrenco",
        "nome_razao_social": "Agrenco do Brasil S.A.",
        "cnpj": "04.123.890/0001-55",
        "setor": "Agronegócio & Logística",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "0534212-90.2008.8.26.0100",
        "valor_causa": 1200000000.00,
        "administrador_judicial": "Laspro Consultores",
        "status_processual": "Falência Decretada",
        "data_distribuicao": "2008-08-13",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 20000000.0,
            "II - Garantia Real": 380000000.0,
            "III - Quirografário": 780000000.0,
            "IV - ME/EPP": 20000000.0,
        },
        "marcos": [
            {
                "data_evento": "2008-08-13",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Trading Agrícola Agrenco",
                "autor": "RECUPERANDA",
                "descricao": "Primeiro caso emblemático de grande empresa com BDRs listados na B3 a ajuizar recuperação judicial.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "grupo-dedini",
        "nome_razao_social": "Dedini S.A. Indústrias de Base",
        "cnpj": "54.123.456/0001-01",
        "setor": "Bens de Capital & Metalurgia",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara Cível da Comarca de Piracicaba / SP",
        "numero_cnj": "1004567-90.2015.8.26.0451",
        "valor_causa": 1200000000.00,
        "administrador_judicial": "AJ Ruiz Consultoria Empresarial",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2015-08-24",
        "url_detalhe": "https://ajruiz.com.br",
        "classes_passivo": {
            "I - Trabalhista": 110000000.0,
            "II - Garantia Real": 350000000.0,
            "III - Quirografário": 690000000.0,
            "IV - ME/EPP": 50000000.0,
        },
        "marcos": [
            {
                "data_evento": "2015-08-24",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Histórica Fabricante de Usinas",
                "autor": "RECUPERANDA",
                "descricao": "Empresa centenária fornecedora de 80% das usinas de açúcar e álcool do país busca reestruturação.",
                "url_documento": "https://ajruiz.com.br",
            },
        ],
    },
    {
        "slug": "grupo-sperafico",
        "nome_razao_social": "Sperafico Agroindustrial S.A.",
        "cnpj": "77.123.456/0001-89",
        "setor": "Agronegócio & Grãos",
        "tribunal": "TJPR",
        "vara_comarca": "1ª Vara Cível da Comarca de Toledo / PR",
        "numero_cnj": "0005678-12.2009.8.16.0170",
        "valor_causa": 1100000000.00,
        "administrador_judicial": "Brizola e Japur Administradora Judicial",
        "status_processual": "Plano Homologado / Venda de Ativos",
        "data_distribuicao": "2009-11-20",
        "url_detalhe": "https://brizolajapur.com.br",
        "classes_passivo": {
            "I - Trabalhista": 35000000.0,
            "II - Garantia Real": 380000000.0,
            "III - Quirografário": 655000000.0,
            "IV - ME/EPP": 30000000.0,
        },
        "marcos": [
            {
                "data_evento": "2009-11-20",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial da Sperafico",
                "autor": "RECUPERANDA",
                "descricao": "Grupo paranaense de esmagamento de soja e óleos vegetais reestrutura passivo bilionário.",
                "url_documento": "https://brizolajapur.com.br",
            },
        ],
    },
    {
        "slug": "lupatech",
        "nome_razao_social": "Lupatech S.A. - Em Recuperação Judicial",
        "cnpj": "89.468.375/0001-97",
        "setor": "Metalurgia & Petróleo",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1049567-34.2015.8.26.0100",
        "valor_causa": 1100000000.00,
        "administrador_judicial": "PwC (PricewaterhouseCoopers)",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2015-05-25",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 25000000.0,
            "II - Garantia Real": 280000000.0,
            "III - Quirografário": 775000000.0,
            "IV - ME/EPP": 20000000.0,
        },
        "marcos": [
            {
                "data_evento": "2015-05-25",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Fabricante de Válvulas Industriais",
                "autor": "RECUPERANDA",
                "descricao": "Fornecedora da Petrobras reestrutura obrigações e emite debêntures conversíveis.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "inepar-sa",
        "nome_razao_social": "Inepar S.A. Indústria e Construções",
        "cnpj": "76.491.234/0001-09",
        "setor": "Equipamentos Industriais & Infraestrutura",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1078456-78.2014.8.26.0100",
        "valor_causa": 2200000000.00,
        "administrador_judicial": "Laspro Consultores",
        "status_processual": "Plano Homologado / Fase de Liquidação",
        "data_distribuicao": "2014-08-01",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 90000000.0,
            "II - Garantia Real": 550000000.0,
            "III - Quirografário": 1510000000.0,
            "IV - ME/EPP": 50000000.0,
        },
        "marcos": [
            {
                "data_evento": "2014-08-01",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação do Grupo Inepar",
                "autor": "RECUPERANDA",
                "descricao": "Conglomerado industrial de turbinas e telecomunicações busca proteção judicial.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "grupo-isolux-corsan",
        "nome_razao_social": "Isolux Corsán do Brasil e Outras",
        "cnpj": "05.678.901/0001-23",
        "setor": "Infraestrutura & Energia",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1089234-45.2016.8.26.0100",
        "valor_causa": 2800000000.00,
        "administrador_judicial": "Alvarez & Marsal",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2016-10-14",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 40000000.0,
            "II - Garantia Real": 750000000.0,
            "III - Quirografário": 1960000000.0,
            "IV - ME/EPP": 50000000.0,
        },
        "marcos": [
            {
                "data_evento": "2016-10-14",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Espanhola Isolux Corsán",
                "autor": "RECUPERANDA",
                "descricao": "Crise de financiamento em projetos de transmissão de energia no Norte e Nordeste.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "engevix-engenharia",
        "nome_razao_social": "Nova Participações S.A. (antiga Engevix Engenharia)",
        "cnpj": "00.123.456/0001-78",
        "setor": "Engenharia & Projetos Industriais",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1118234-56.2015.8.26.0100",
        "valor_causa": 2400000000.00,
        "administrador_judicial": "Brizola e Japur Administradora Judicial",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2015-11-23",
        "url_detalhe": "https://brizolajapur.com.br",
        "classes_passivo": {
            "I - Trabalhista": 55000000.0,
            "II - Garantia Real": 650000000.0,
            "III - Quirografário": 1645000000.0,
            "IV - ME/EPP": 50000000.0,
        },
        "marcos": [
            {
                "data_evento": "2015-11-23",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Projetista Engevix",
                "autor": "RECUPERANDA",
                "descricao": "Empresa de consultoria e engenharia de barragens e plantas industriais busca proteção.",
                "url_documento": "https://brizolajapur.com.br",
            },
        ],
    },
    {
        "slug": "grupo-ccrr",
        "nome_razao_social": "Grupo CCRR (Colacril e Baumgarten)",
        "cnpj": "50.123.456/0001-99",
        "setor": "Embalagens & Etiquetas",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara Cível da Comarca de Salto / SP",
        "numero_cnj": "1002345-12.2023.8.26.0526",
        "valor_causa": 800000000.00,
        "administrador_judicial": "AJ Ruiz Consultoria Empresarial",
        "status_processual": "Plano Homologado Judicialmente",
        "data_distribuicao": "2023-04-10",
        "url_detalhe": "https://ajruiz.com.br",
        "classes_passivo": {
            "I - Trabalhista": 25000000.0,
            "II - Garantia Real": 280000000.0,
            "III - Quirografário": 470000000.0,
            "IV - ME/EPP": 25000000.0,
        },
        "marcos": [
            {
                "data_evento": "2023-04-10",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação do Grupo CCRR",
                "autor": "RECUPERANDA",
                "descricao": "Líder na América Latina em autoadesivos e etiquetas reestrutura passivo financeiro.",
                "url_documento": "https://ajruiz.com.br",
            },
        ],
    },
    {
        "slug": "saraiva-livreiros",
        "nome_razao_social": "Saraiva Livreiros S.A. - Em Recuperação Judicial",
        "cnpj": "61.365.284/0001-49",
        "setor": "Varejo & Livraria",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1119642-14.2018.8.26.0100",
        "valor_causa": 675000000.00,
        "administrador_judicial": "EXM Partners",
        "status_processual": "Falência Decretada",
        "data_distribuicao": "2018-11-23",
        "url_detalhe": "https://exmpartners.com.br",
        "classes_passivo": {
            "I - Trabalhista": 40000000.0,
            "II - Garantia Real": 120000000.0,
            "III - Quirografário": 485000000.0,
            "IV - ME/EPP": 30000000.0,
        },
        "marcos": [
            {
                "data_evento": "2018-11-23",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Maior Rede de Livrarias do País",
                "autor": "RECUPERANDA",
                "descricao": "Rede tradicional de livrarias com mais de 100 anos busca reestruturação frente ao avanço do e-commerce.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
            {
                "data_evento": "2023-10-06",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Sentença de Falência da Saraiva",
                "autor": "JUIZO",
                "descricao": "2ª Vara de Falências de SP decreta a falência da companhia a pedido da própria recuperanda.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "cruzeiro-esporte-clube",
        "nome_razao_social": "Cruzeiro Esporte Clube (Associação / SAF)",
        "cnpj": "17.234.567/0001-33",
        "setor": "Futebol & Entretenimento (SAF)",
        "tribunal": "TJMG",
        "vara_comarca": "1ª Vara Empresarial da Comarca de Belo Horizonte / MG",
        "numero_cnj": "5145678-90.2022.8.13.0024",
        "valor_causa": 530000000.00,
        "administrador_judicial": "Inocêncio de Paula Sociedade de Advogados",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2022-07-11",
        "url_detalhe": "https://tjmg.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 180000000.0,
            "II - Garantia Real": 40000000.0,
            "III - Quirografário": 290000000.0,
            "IV - ME/EPP": 20000000.0,
        },
        "marcos": [
            {
                "data_evento": "2022-07-11",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Primeiro Grande Clube Brasileiro a Ajuizar Recuperação Judicial",
                "autor": "RECUPERANDA",
                "descricao": "Associação civil Cruzeiro ingressa com RJ após cisão dos ativos de futebol para a SAF adquirida por Ronaldo Nazário.",
                "url_documento": "https://tjmg.jus.br",
            },
            {
                "data_evento": "2023-08-18",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Homologação do Plano de Recuperação do Cruzeiro",
                "autor": "JUIZO",
                "descricao": "Plano homologado viabiliza o pagamento dos credores trabalhistas e quirografários através das receitas da SAF.",
                "url_documento": "https://tjmg.jus.br",
            },
        ],
    },
    {
        "slug": "grupo-rodrimar",
        "nome_razao_social": "Grupo Rodrimar (Rodrimar S.A. Transportes e Terminais)",
        "cnpj": "58.123.456/0001-77",
        "setor": "Portos & Logística",
        "tribunal": "TJSP",
        "vara_comarca": "6ª Vara Cível da Comarca de Santos / SP",
        "numero_cnj": "1023456-78.2018.8.26.0562",
        "valor_causa": 400000000.00,
        "administrador_judicial": "Laspro Consultores",
        "status_processual": "Falência Decretada",
        "data_distribuicao": "2018-11-05",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 45000000.0,
            "II - Garantia Real": 80000000.0,
            "III - Quirografário": 255000000.0,
            "IV - ME/EPP": 20000000.0,
        },
        "marcos": [
            {
                "data_evento": "2018-11-05",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação de Operador Tradicional no Porto de Santos",
                "autor": "RECUPERANDA",
                "descricao": "Operadora portuária de armazéns e retroárea pede proteção judicial.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "polishop",
        "nome_razao_social": "Polimport Comércio e Exportação Ltda. (Polishop)",
        "cnpj": "00.436.042/0001-22",
        "setor": "Varejo Multicanal & Eletrodomésticos",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1064234-89.2024.8.26.0100",
        "valor_causa": 352000000.00,
        "administrador_judicial": "Laspro Consultores",
        "status_processual": "Processamento Deferido / Em Negociação",
        "data_distribuicao": "2024-05-17",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 30000000.0,
            "II - Garantia Real": 65000000.0,
            "III - Quirografário": 232000000.0,
            "IV - ME/EPP": 25000000.0,
        },
        "marcos": [
            {
                "data_evento": "2024-05-17",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial da Polishop",
                "autor": "RECUPERANDA",
                "descricao": "Rede pioneira em televendas e shopping centers ajuíza recuperação após fechamento de mais de 100 lojas.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
            {
                "data_evento": "2024-05-23",
                "tipo_evento": "DECISAO_PROCESSAMENTO",
                "titulo": "Decisão de Processamento na 2ª Vara de Falências",
                "autor": "JUIZO",
                "descricao": "Juízo de SP defere processamento e determina suspensão de ações de despejo em shoppings.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "livraria-cultura",
        "nome_razao_social": "Livraria Cultura S.A. e 3F Comércio de Livros",
        "cnpj": "62.410.352/0001-72",
        "setor": "Varejo & Livraria",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1110406-09.2018.8.26.0100",
        "valor_causa": 285000000.00,
        "administrador_judicial": "Alvarez & Marsal",
        "status_processual": "Falência Decretada / Fechamento de Lojas",
        "data_distribuicao": "2018-10-24",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 18000000.0,
            "II - Garantia Real": 45000000.0,
            "III - Quirografário": 207000000.0,
            "IV - ME/EPP": 15000000.0,
        },
        "marcos": [
            {
                "data_evento": "2018-10-24",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação da Icônica Livraria Cultura",
                "autor": "RECUPERANDA",
                "descricao": "Rede proprietária da lendária loja do Conjunto Nacional na Av. Paulista ajuíza recuperação judicial.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
            {
                "data_evento": "2023-02-09",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Sentença de Decretação de Falência",
                "autor": "JUIZO",
                "descricao": "Juiz Ralpho de Barros Monteiro Filho decreta falência após descumprimento sucessivo de obrigações do plano.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "coritiba-foot-ball-club",
        "nome_razao_social": "Coritiba Foot Ball Club (Associação / SAF)",
        "cnpj": "76.123.456/0001-90",
        "setor": "Futebol & Esportes (SAF)",
        "tribunal": "TJPR",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais de Curitiba / PR",
        "numero_cnj": "0012890-34.2022.8.16.0185",
        "valor_causa": 120000000.00,
        "administrador_judicial": "Brizola e Japur Administradora Judicial",
        "status_processual": "Plano Homologado com Êxito",
        "data_distribuicao": "2022-03-14",
        "url_detalhe": "https://brizolajapur.com.br",
        "classes_passivo": {
            "I - Trabalhista": 45000000.0,
            "II - Garantia Real": 15000000.0,
            "III - Quirografário": 52000000.0,
            "IV - ME/EPP": 8000000.0,
        },
        "marcos": [
            {
                "data_evento": "2022-03-14",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial do Clube Paranaense",
                "autor": "RECUPERANDA",
                "descricao": "Ajuizamento preventivo para blindagem antes da conclusão da venda da SAF para o fundo Treecorp.",
                "url_documento": "https://brizolajapur.com.br",
            },
        ],
    },
    {
        "slug": "grupo-lock",
        "nome_razao_social": "Athol Participações Ltda. (Grupo Lock Engenharia)",
        "cnpj": "03.123.456/0001-11",
        "setor": "Construção Civil & Engenharia",
        "tribunal": "TJSP",
        "vara_comarca": "2ª Vara de Falências e Recuperações Judiciais - Foro Central Cível",
        "numero_cnj": "1024564-80.2024.8.26.0100",
        "valor_causa": 145000000.00,
        "administrador_judicial": "AJ Ruiz Consultoria Empresarial",
        "status_processual": "Processamento Deferido / Em Andamento",
        "data_distribuicao": "2024-03-05",
        "url_detalhe": "https://esaj.tjsp.jus.br/cpopg/show.do?processo.numero=1024564-80.2024.8.26.0100",
        "classes_passivo": {
            "I - Trabalhista": 12000000.0,
            "II - Garantia Real": 35000000.0,
            "III - Quirografário": 88000000.0,
            "IV - ME/EPP": 10000000.0,
        },
        "marcos": [
            {
                "data_evento": "2024-03-05",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial do Grupo Lock",
                "autor": "RECUPERANDA",
                "descricao": "Empresa especializada em obras corporativas de alto padrão ingressa com pedido na capital paulista.",
                "url_documento": "https://ajruiz.com.br",
            },
            {
                "data_evento": "2024-03-20",
                "tipo_evento": "DECISAO_PROCESSAMENTO",
                "titulo": "Processamento Deferido na 2ª Vara de Falências de SP",
                "autor": "JUIZO",
                "descricao": "Juízo defere o processamento e nomeia AJ Ruiz Consultoria Empresarial.",
                "url_documento": "https://ajruiz.com.br",
            },
        ],
    },
    {
        "slug": "atlas-agroindustrial-ltda",
        "nome_razao_social": "Atlas Agroindustrial Ltda.",
        "cnpj": "10.456.789/0001-02",
        "setor": "Agronegócio & Grãos",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara Cível da Comarca de Matão / SP",
        "numero_cnj": "1001234-56.2023.8.26.0347",
        "valor_causa": 115000000.00,
        "administrador_judicial": "AJ Ruiz Consultoria Empresarial",
        "status_processual": "Recuperação Extrajudicial Homologada",
        "data_distribuicao": "2023-08-15",
        "url_detalhe": "https://ajruiz.com.br",
        "classes_passivo": {
            "I - Trabalhista": 0.0,
            "II - Garantia Real": 42000000.0,
            "III - Quirografário": 73000000.0,
            "IV - ME/EPP": 0.0,
        },
        "marcos": [
            {
                "data_evento": "2023-08-15",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Homologação de Plano de Recuperação Extrajudicial",
                "autor": "RECUPERANDA",
                "descricao": "Ajuizamento com quórum qualificado de credores financeiros e fornecedores de grãos.",
                "url_documento": "https://ajruiz.com.br",
            },
            {
                "data_evento": "2023-11-28",
                "tipo_evento": "HOMOLOGACAO",
                "titulo": "Sentença de Homologação da Recuperação Extrajudicial",
                "autor": "JUIZO",
                "descricao": "Juízo de Matão chancela os termos negociados com novação das dívidas bancárias.",
                "url_documento": "https://ajruiz.com.br",
            },
        ],
    },
    {
        "slug": "botafogo-de-futebol-e-regatas",
        "nome_razao_social": "Botafogo de Futebol e Regatas (Regime Centralizado de Execuções)",
        "cnpj": "34.123.456/0001-89",
        "setor": "Futebol & Entretenimento (SAF)",
        "tribunal": "TJRJ",
        "vara_comarca": "Tribunal de Justiça do Estado do Rio de Janeiro / RCE",
        "numero_cnj": "0801234-56.2021.8.19.0001",
        "valor_causa": 400000000.00,
        "administrador_judicial": "Preserva-Ação",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2021-10-01",
        "url_detalhe": "https://tjrj.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 220000000.0,
            "II - Garantia Real": 0.0,
            "III - Quirografário": 180000000.0,
            "IV - ME/EPP": 0.0,
        },
        "marcos": [
            {
                "data_evento": "2021-10-01",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Instauração do Regime Centralizado de Execuções (Lei da SAF)",
                "autor": "RECUPERANDA",
                "descricao": "Centralização das execuções trabalhistas e cíveis com destinação de 20% das receitas correntes da SAF.",
                "url_documento": "https://tjrj.jus.br",
            },
        ],
    },
    {
        "slug": "ambipar-participacoes",
        "nome_razao_social": "Ambipar Participações e Empreendimentos S.A.",
        "cnpj": "12.648.266/0001-24",
        "setor": "Gestão Ambiental & Resíduos",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara de Falências e Recuperações Judiciais / SP",
        "numero_cnj": "1045678-90.2024.8.26.0100",
        "valor_causa": 1500000000.00,
        "administrador_judicial": "Kroll Brasil",
        "status_processual": "Monitoramento de Mercado / Reestruturação",
        "data_distribuicao": "2024-07-01",
        "url_detalhe": "https://esaj.tjsp.jus.br",
        "classes_passivo": {
            "I - Trabalhista": 30000000.0,
            "II - Garantia Real": 420000000.0,
            "III - Quirografário": 1020000000.0,
            "IV - ME/EPP": 30000000.0,
        },
        "marcos": [
            {
                "data_evento": "2024-07-01",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Reestruturação Financeira e Operacional",
                "autor": "RECUPERANDA",
                "descricao": "Monitoramento preventivo e renegociação de debêntures no mercado de capitais.",
                "url_documento": "https://esaj.tjsp.jus.br",
            },
        ],
    },
    {
        "slug": "grupo-tg-agro-industrial",
        "nome_razao_social": "TG Agro Industrial Ltda. e TG Participações S.A.",
        "cnpj": "18.123.456/0001-50",
        "setor": "Agronegócio & Açúcar",
        "tribunal": "TJSP",
        "vara_comarca": "1ª Vara Cível da Comarca de Lençóis Paulista / SP",
        "numero_cnj": "1003456-78.2023.8.26.0319",
        "valor_causa": 210000000.00,
        "administrador_judicial": "AJ Ruiz Consultoria Empresarial",
        "status_processual": "Plano Homologado / Em Cumprimento",
        "data_distribuicao": "2023-05-10",
        "url_detalhe": "https://ajruiz.com.br",
        "classes_passivo": {
            "I - Trabalhista": 15000000.0,
            "II - Garantia Real": 65000000.0,
            "III - Quirografário": 120000000.0,
            "IV - ME/EPP": 10000000.0,
        },
        "marcos": [
            {
                "data_evento": "2023-05-10",
                "tipo_evento": "PETICAO_INICIAL",
                "titulo": "Pedido de Recuperação Judicial do Grupo TG",
                "autor": "RECUPERANDA",
                "descricao": "Usina de cana-de-açúcar e etanol ajuíza recuperação com passivo de R$ 210 milhões.",
                "url_documento": "https://ajruiz.com.br",
            },
        ],
    },
]
